apiVersion: v1
kind: Pod
metadata:
  name: test-yolo-pod
spec:
  containers:
  - name: test-yolo-container
    image: nekhilnagia16/yolov7:latest
    command: ["sleep", "3600"]
    resources:
      limits:
        nvidia.com/gpu: 1
  restartPolicy: Never
  runtimeClassName: nvidia
